name: Deploy Api

on: [push]

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      pull-requests: read
      packages: read
      # Required for Azure OIDC login
      id-token: write
    
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} 
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }} 
      ARM_TENANT_ID: ${{ secrets.AAD_TENANT }} 

    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      
    - uses: actions/checkout@v2

    - name: show user
      run: |
        az webapp list