name: Deploy Api

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish GHSample.Api/ghactions.csproj -c Release -o api
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: api
        path: api/**
        if-no-files-found: error
  deploy:
    permissions:
      actions: read
      contents: read
      pull-requests: read
      packages: read
      # Required for Azure OIDC login
      id-token: write
    
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} 
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }} 
      ARM_TENANT_ID: ${{ secrets.AAD_TENANT }} 
      app-name: ghtestapi2
    
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: api
        path: api

    - uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}      

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        slot-name: staging
        package: api